version: '3'
volumes:
  caddy: {}

services:
  mailer: &mailer
    image: kelvinsantos/go-mailer:latest
    env_file:
      - .env
    ports:
      - "9090:9090"

  remark:
    image: umputun/docker-logger
    container_name: "streamer_logger"
    hostname: "logger"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - LOG_FILES=true
      - LOG_SYSLOG=false
      - EXCLUDE=monit,docker-logger
      - MAX_FILES=10
      - MAX_SIZE=50
      - MAX_AGE=20
      - DEBUG=false
      - TIME_ZONE=Asia/Singapore

    volumes:
      - ./logs:/srv/logs
      - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    build:
      context: .
      dockerfile: ./docker_compose/caddy/Dockerfile
    depends_on:
      - mailer
    volumes:
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - "0.0.0.0:443:443"