package env

var GO_MAILER_AUTH_SECRET string
var GO_MAILER_AWS_ACCESS_KEY string
var GO_MAILER_AWS_SECRET_KEY string
var GO_MAILER_AWS_REGION string
var GO_MAILER_PORT string
var GO_MOCK_EMAIL string